version: '3'
networks:
  weplan:
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: weplan
      MYSQL_DATABASE: weplan
      MYSQL_USER: weplan
      MYSQL_PASSWORD: weplan
    ports:
    - "3306:3306"
    networks:
    - weplan
  web:
    image: "gm/weplan:1.0-SNAPSHOT"
    ports:
    - "8080:8080"
    networks:
    - weplan
    depends_on:
    - db